# Generated by Django 5.1.7 on 2025-04-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='type',
            new_name='item_type',
        ),
    ]
