# Generated by Django 5.1.7 on 2025-05-16 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_date',
            field=models.DateField(default=datetime.date(2025, 5, 17)),
        ),
    ]
