# Generated by Django 5.1.7 on 2025-04-25 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_ratings_review_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='watch_date',
            field=models.DateField(default=datetime.date(2025, 4, 25)),
        ),
    ]
