# Generated by Django 5.1.7 on 2025-04-27 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_reviews_watch_date_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_date',
            field=models.DateField(default=datetime.date(2025, 4, 27)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='watch_date',
            field=models.DateField(blank=True),
        ),
    ]
