# Generated by Django 5.1.7 on 2025-04-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_reviews_review_date_alter_reviews_watch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='watch_date',
            field=models.DateField(null=True),
        ),
    ]
