# Generated by Django 5.1.7 on 2025-04-28 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_date',
            field=models.DateField(default=datetime.date(2025, 4, 28)),
        ),
    ]
