# Generated by Django 5.1.7 on 2025-05-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=20)),
                ('book_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CachedBookQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('genres', models.TextField()),
                ('book_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CachedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_data', models.JSONField()),
                ('content', models.TextField(blank=True, null=True)),
                ('substance', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CachedMovieQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('years', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('genres', models.TextField()),
                ('movie_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CachedMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=20)),
                ('movie_data', models.JSONField()),
            ],
        ),
    ]
