# Generated by Django 5.1.7 on 2025-04-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedMovieQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('years', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=20)),
                ('genres', models.TextField()),
                ('item_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='popularBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_data', models.JSONField()),
            ],
        ),
    ]
