# Generated by Django 5.1.7 on 2025-05-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedbooks',
            name='covers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
