# Generated by Django 5.1.7 on 2025-05-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedbooks',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedbooks',
            name='substance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
