# Generated by Django 5.1.7 on 2025-05-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_cachedbooks_covers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedbooks',
            name='covers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
