# Generated by Django 5.1.7 on 2025-05-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_cachedbooks_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedbooks',
            name='substance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
