# Generated by Django 5.1.7 on 2025-04-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_cachedmoviequeries_popularbooks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cachedmoviequeries',
            old_name='item_data',
            new_name='movie_data',
        ),
        migrations.AlterField(
            model_name='cachedmoviequeries',
            name='years',
            field=models.CharField(max_length=20),
        ),
    ]
