# Generated by Django 5.1.7 on 2025-04-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_rename_item_data_cachedmoviequeries_movie_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_data', models.JSONField()),
            ],
        ),
    ]
