# Generated by Django 5.1.7 on 2025-04-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_moviecollections_delete_newmovies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviecollections',
            old_name='movies_list',
            new_name='movie_data',
        ),
    ]
