# Generated by Django 5.1.7 on 2025-05-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_rename_movies_list_moviecollections_movie_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=20)),
                ('book_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CachedBookQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('genres', models.TextField()),
                ('book_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CachedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_data', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='popularBooks',
        ),
    ]
