# Generated by Django 5.1.7 on 2025-04-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_bookcollections_delete_popularbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedBookQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('years', models.CharField(max_length=20)),
                ('genres', models.TextField()),
                ('book_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CachedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_data', models.JSONField()),
            ],
        ),
    ]
