# Generated by Django 5.1.7 on 2025-04-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_cachedbookqueries_cachedbooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachedbookqueries',
            name='years',
        ),
    ]
