# Generated by Django 5.1.7 on 2025-05-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Decade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_movie_recommendations', models.TextField(blank=True, null=True)),
                ('saved_book_recommendations', models.TextField(blank=True, null=True)),
                ('book_recommendations_updated', models.DateTimeField(blank=True, null=True)),
                ('movie_recommendations_updated', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_movie_genres', models.JSONField(blank=True, default=list)),
                ('last_viewed_book_genres', models.JSONField(blank=True, default=list)),
                ('last_viewed_countries', models.JSONField(blank=True, default=list)),
                ('last_viewed_authors', models.JSONField(blank=True, default=list)),
                ('last_viewed_directors', models.JSONField(blank=True, default=list)),
                ('favorite_book_authors', models.ManyToManyField(related_name='book_authors_users', to='preferences.bookauthor')),
                ('favorite_book_decades', models.ManyToManyField(related_name='book_decade_users', to='preferences.decade')),
                ('favorite_book_genres', models.ManyToManyField(related_name='book_users', to='preferences.bookgenre')),
                ('favorite_countries', models.ManyToManyField(related_name='country_users', to='preferences.country')),
                ('favorite_movie_decades', models.ManyToManyField(related_name='movie_decade_users', to='preferences.decade')),
                ('favorite_movie_directors', models.ManyToManyField(related_name='movie_directors_users', to='preferences.moviedirector')),
                ('favorite_movie_genres', models.ManyToManyField(related_name='movie_users', to='preferences.moviegenre')),
            ],
        ),
    ]
