# Generated by Django 5.1.7 on 2025-04-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre'},
        ),
        migrations.AlterModelOptions(
            name='preference',
            options={'verbose_name': 'Preference'},
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='genre_name',
        ),
        migrations.AddField(
            model_name='preference',
            name='favorite_book_name',
            field=models.ManyToManyField(related_name='shit2', to='preferences.country'),
        ),
        migrations.AddField(
            model_name='preference',
            name='favorite_movie_name',
            field=models.ManyToManyField(related_name='shit', to='preferences.country'),
        ),
    ]
