# Generated by Django 5.1.7 on 2025-04-27 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_country_alter_genre_options_alter_preference_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_name',
            new_name='name',
        ),
    ]
