# Generated by Django 5.1.7 on 2025-05-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='book_recommendations_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='movie_recommendations_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
