# Generated by Django 5.1.7 on 2025-05-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_preference_book_recommendations_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preference',
            options={'verbose_name': 'Предпочтения пользователя', 'verbose_name_plural': 'Предпочтения пользователей'},
        ),
        migrations.AddField(
            model_name='preference',
            name='last_viewed_authors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='preference',
            name='last_viewed_book_genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='preference',
            name='last_viewed_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='preference',
            name='last_viewed_directors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='preference',
            name='last_viewed_movie_genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
