# Generated by Django 5.1.7 on 2025-04-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_rename_genre_name_genre_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Жанр фильма',
            },
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='BookGenre',
        ),
        migrations.AlterModelOptions(
            name='bookgenre',
            options={'verbose_name': 'Жанр книги'},
        ),
        migrations.AlterModelOptions(
            name='preference',
            options={'verbose_name': 'Предпочтения'},
        ),
        migrations.RemoveField(
            model_name='preference',
            name='favorite_book_name',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='favorite_movie_name',
        ),
        migrations.AddField(
            model_name='preference',
            name='favorite_countries',
            field=models.ManyToManyField(related_name='country_users', to='preferences.country'),
        ),
        migrations.AddField(
            model_name='preference',
            name='favorite_book_decades',
            field=models.ManyToManyField(related_name='book_decade_users', to='preferences.decade'),
        ),
        migrations.AddField(
            model_name='preference',
            name='favorite_movie_decades',
            field=models.ManyToManyField(related_name='movie_decade_users', to='preferences.decade'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='favorite_movie_genres',
            field=models.ManyToManyField(related_name='movie_users', to='preferences.moviegenre'),
        ),
    ]
