# Generated by Django 5.1.7 on 2025-04-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_decade_moviegenre_rename_genre_bookgenre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookgenre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='moviegenre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='preference',
            options={},
        ),
        migrations.AddField(
            model_name='preference',
            name='favorite_book_authors',
            field=models.ManyToManyField(blank=True, to='preferences.bookauthor'),
        ),
        migrations.AddField(
            model_name='preference',
            name='favorite_movie_directors',
            field=models.ManyToManyField(blank=True, to='preferences.moviedirector'),
        ),
    ]
