# Generated by Django 5.1.7 on 2025-05-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_alter_preference_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preference',
            options={},
        ),
    ]
