# Generated by Django 5.1.7 on 2025-04-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0005_bookauthor_moviedirector_alter_bookgenre_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='name',
        ),
    ]
