# Generated by Django 5.1.7 on 2025-05-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0006_rename_country_name_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='saved_book_recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='saved_movie_recommendations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
